name:       line-type
version:    0.1.0.0
github:     kshepard/line-type
license:    MIT
author:     'Kenneth Shepard'
maintainer: kshepard@gmail.com
copyright:  '2018 Kenneth Shepard'

extra-source-files:
  - README.md

synopsis: 'Generative art in Haskell'
category: Art
description: 'See the README at <https://github.com/kshepard/line-type#readme>'

ghc-options:
  -fwarn-unused-imports
  -fwarn-unused-binds
  -fwarn-name-shadowing
  -fwarn-unused-matches
  -fwarn-incomplete-patterns
  -fwarn-incomplete-uni-patterns

dependencies:
  - base

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators

library:
  source-dirs: src
  dependencies:
      - servant
      - text

executables:
  line-type-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - line-type
      - servant-server
      - wai
      - warp

tests:
  line-type-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
